openapi: 3.0.3
info:
  title: API pública
  version: "1.0"
  description: Practica exploratoria de AD
  contact:
    email: andres.leandro.guizzo@estudiantat.upc.edu
  license:
    name: Glassfish 5.1.0
    url: https://javaee.github.io/glassfish/LICENSE
servers:
  - url: http://localhost:8080/RESTService/resources
tags:
  - name: user
    description: Operaciones sobre usuarios
  - name: image
    description: Operaciones sobre imágenes

paths:
  /user/register:
    post:
      tags:
        - user
      summary: Registra un nuevo usuario
      description: Registra un nuevo usuario con el nombre de usuario y contraseña indicados
      operationId: userRegister
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#components/schemas/User"
        required: true
      responses:
        default:
          description: Usuario registrado con éxito
          content:
            application/json:
              schema:
                $ref: "#components/schemas/User"
        "201":
          description: Usuario registrado con éxito
        "409":
          description: Ya existe un usuario con ese nombre
        
  

  /image/{Id}:
    get:
      tags:
        - image
      summary: Busca una imagen por ID
      description: Devuelve los datos de la imagen con el ID indicado
      operationId: searchImageById
      parameters:
        - name: Id
          in: path
          description: ID de la imagen
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Imagen encontrada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'          
        '404':
          description: La imagen no existe
    put: 
      tags:
        - image
      summary: Modifica los metadatos de una imagen
      description: Modifica los metadatos según el valor de los parámetros indicados
      operationId: imageModify
      parameters:
        - name: Id
          in: path
          description: ID de la imagen
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#components/schemas/ImageModify"
        required: true
      responses:
        '200':
          description: Imagen modificada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'   
        '403':
          description: No puedes modificar imáganes de otros usuarios
        '404':
          description: La imagen no existe
  /image/list:
    get:
      tags:
        - image
      summary: Devuelve todas las imágenes
      description: Devuelve una lista de todas las imágenes existentes
      operationId: listImages
      responses:
        '200':
          description: Imágenes encontradas con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Image'
  /image/getImage/{Id}:
    get:
      tags:
        - image
      summary: Descarga una imagen
      description: Devuelve el fichero correspondiente a la imagen con el ID indicado
      operationId: downloadImage
      parameters:
        - name: Id
          in: path
          description: ID de la imagen
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Imagen descargada con éxito
          content:
            image/*:
               schema:
                  type: string
                  format: binary
        '404':
          description: La imagen no existe




components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          description: Nombre del usuario
          example: "Andres"
        password:
          type: string
          description: Contraseña del usuario
          example: "12345"
    Image:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador de una imagen
          example: 2
        title:
          type: string
          description: Título de la imagen
          example: Gato
        description:
          type: string
          description: Descripción de la imagen
          example: Imagen de un gato pequeño
        keywords:
          type: string
          description: Palabras que sirven para clasificar la imagen
          example: animal gato
        author:
          type: string
          description: Nombre del autor de la imagen
          example: Juan
        uploader:
          type: string
          description: Nombre del usuario que ha subido la imagen
          example: Andres
        captureDate:
          type: string
          format: date
          description: Fecha de captura de la imagen, formato YYYY-MM-DD
          example: "2022-11-10"
        storageDate:
          type: string
          format: date
          description: Fecha de subida de la imagen, formato YYYY-MM-DD
          example: "2022-11-26"
        fileName:
          type: string
          description: Nombre del fichero de la imagen
          example: gato.jpg
    ImageModify:
      type: object
      properties:
        title:
          type: string
          description: Título de la imagen
          example: Gato
        description:
          type: string
          description: Descripción de la imagen
          example: Imagen de un gato pequeño
        keywords:
          type: string
          description: Palabras que sirven para clasificar la imagen
          example: animal gato
        author:
          type: string
          description: Nombre del autor de la imagen
          example: Juan
        uploader:
          type: string
          description: Nombre del usuario que ha subido la imagen
          example: Andres
        captureDate:
          type: string
          format: date
          description: Fecha de captura de la imagen, formato YYYY-MM-DD
          example: "2022-11-10"



