openapi: 3.0.3
info:
  title: API pública
  version: "1.0"
  description: Practica exploratoria de AD, desarrollada por Andrés Leandro y Moisés Balcells
  contact:
    email: andres.leandro.guizzo@estudiantat.upc.edu
servers:
  - url: http://localhost:8080/RESTService/resources
tags:
  - name: user
    description: Operaciones sobre usuarios
  - name: image
    description: Operaciones sobre imágenes

paths:
  /user/register:
    post:
      tags:
        - user
      summary: Registra un nuevo usuario
      description: Registra un nuevo usuario con el nombre de usuario y contraseña indicados
      operationId: userRegister
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#components/schemas/UserForm"
        required: true
      responses:
        "201":
          description: Usuario registrado con éxito
          content:
            application/json:
              schema:
                $ref: "#components/schemas/User"
        "409":
          description: Ya existe un usuario con ese nombre
  /user/login:
    post:
      tags:
        - user
      summary: Haz login
      description: Inicia sesión con el nombre de usuario y contraseña indicados
      operationId: userLogin
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/UserForm"
        required: true
      responses:
        default:
          description: Inicio sesión éxitoso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "201":
          description: Usuario registrado con éxito
        "404":
          description: El nombre de usuario o la contraseña son incorrectos.
       
  /image/{Id}:
    get:
      tags:
        - image
      summary: Busca una imagen por ID
      description: Devuelve los datos de la imagen con el ID indicado
      operationId: searchImageById
      parameters:
        - name: Id
          in: path
          description: ID de la imagen
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Imagen encontrada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'          
        '404':
          description: La imagen no existe
    put: 
      tags:
        - image
      summary: Modifica los metadatos de una imagen
      description: Modifica los metadatos según el valor de los parámetros indicados
      operationId: imageModify
      parameters:
        - name: Id
          in: path
          description: ID de la imagen
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#components/schemas/ImageModifyForm"
        required: true
      responses:
        '200':
          description: Imagen modificada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'   
        '403':
          description: No puedes modificar imáganes de otros usuarios
        '404':
          description: La imagen no existe
      security:
        - api_key: []
    delete:
      tags:
      - image
      summary: Elimina una imagen
      description: Elimina una imágen indicando el ID
      operationId: imageDelete
      parameters:
        - name: Id
          in: path
          description: ID de la imagen
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Imagen eliminada con éxito
        '404':
          description: La imagen no existe
        '409': 
          description: No puedes eliminar imáganes de otros usuarios
      security:
        - api_key: []
  /image/list:
    get:
      tags:
        - image
      summary: Devuelve todas las imágenes
      description: Devuelve una lista de todas las imágenes existentes
      operationId: listImages
      responses:
        '200':
          description: Imágenes encontradas con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Image'
  /image/downloadImage/{Id}:
    get:
      tags:
        - image
      summary: Descarga una imagen
      description: Devuelve el fichero correspondiente a la imagen con el ID indicado
      operationId: downloadImage
      parameters:
        - name: Id
          in: path
          description: ID de la imagen
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Imagen descargada con éxito
          content:
            image/*:
               schema:
                  type: string
                  format: binary
        '404':
          description: La imagen no existe
  /image/upload:
    post:
      tags:
        - image
      summary: Subida de una imagen
      description: Devuelve el fichero correspondiente a la imagen con el ID indicado
      operationId: uploadImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#components/schemas/ImageMultipartForm"
      responses:
        '201':
          description: Imagen registrada con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '404':
          description: La imagen no existe
      security:
        - api_key: []
  /image/searchTitle/{title}:
    get:
      tags:
        - image
      summary: Busca una imagen por título
      description: Devuelve los datos de las imágenes que contiene los carácteres indicados en el título
      operationId: searchByTitle
      parameters:
        - name: title
          in: path
          description: Fecha de la imagen
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Imágenes encontradas con éxito 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'      
  /image/searchCreationDate/{date}:
    get:
      tags:
        - image
      summary: Busca una imagen por fecha de almacenamiento
      description: Devuelve los datos de las imágenes que tienen una fecha igual o superior a la indicada
      operationId: searchByStorageDate 
      parameters:
        - name: date
          in: path
          description: Fecha de la imagen, el formato es el siguiente yyyy-mm-dd
          required: true
          schema:
            type: string
            example: "2022-11-26"
      responses:
        '200':
          description: Encontradas con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
  /image/searchAuthor/{author}:
    get:
      tags:
        - image
      summary: Busca una imagen por autor 
      description: Devuelve los datos de las imágenes que contiene el string indicado en el autor
      operationId: searchByAuthor 
      parameters:
        - name: author
          in: path
          description: Autor de la imagen
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Imágenes encontradas con éxito 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'      
  /image/searchKeywords/{keywords}:
    get:
      tags:
        - image
      summary: Busca una imagen por las palabras clave 
      description: Devuelve los datos de las imágenes que contienen las palabras claves indicadas
      operationId: searchByKeywords 
      parameters:
        - name: keywords
          in: path
          description: Palabras clave de la imagen
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Imágenes encontradas con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
  /image/combinedSearch:
    get:
      tags:
        - image
      summary: Busca imágenes por título, palabras clave, autor y fecha de captura 
      description: Devuelve los datos de las imágenes según la búsqueda combinada realizada
      operationId: searchImages 
      parameters:
        - name: title
          in: query
          description: Fecha de la imagen
          schema:
            type: string
          allowEmptyValue: true
        - name: keywords
          in: query
          description: Palabras clave de la imagen
          schema:
            type: string
          allowEmptyValue: true
        - name: author
          in: query
          description: Autor de la imagen
          schema:
            type: string
          allowEmptyValue: true
        - name: captureDate
          in: query
          description: Fecha de captura de la imagen, formato yyyy-mm-dd
          schema:
            type: string
            example: "2022-11-26"
          allowEmptyValue: true
      responses:
        '200':
          description: Imágenes encontradas con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'      
  

components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          description: Nombre del usuario
          example: "Andres"
        password:
          type: string
          description: Contraseña del usuario
          example: "12345"
        token:
          type: string
          description: token de autenticación
          example: 5bad105cc0d831c4f923d6c60c7fe0dd
    UserForm:
      type: object
      properties:
        username:
          type: string
          description: Nombre del usuario
          example: "Andres"
        password:
          type: string
          format: password
          description: Contraseña del usuario
          example: "12345"
    Image:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador de una imagen
          example: 2
        title:
          type: string
          description: Título de la imagen
          example: Gato
        description:
          type: string
          description: Descripción de la imagen
          example: Imagen de un gato pequeño
        keywords:
          type: string
          description: Palabras que sirven para clasificar la imagen
          example: animal gato
        author:
          type: string
          description: Nombre del autor de la imagen
          example: Juan
        uploader:
          type: string
          description: Nombre del usuario que ha subido la imagen
          example: Andres
        captureDate:
          type: string
          format: date
          description: Fecha de captura de la imagen, formato YYYY-MM-DD
          example: "2022-11-10"
        storageDate:
          type: string
          format: date
          description: Fecha de subida de la imagen, formato YYYY-MM-DD
          example: "2022-11-26"
        fileName:
          type: string
          description: Nombre del fichero de la imagen
          example: gato.jpg
    ImageModifyForm:
      type: object
      properties:
        title:
          type: string
          description: Título de la imagen
          example: Gato
        description:
          type: string
          description: Descripción de la imagen
          example: Imagen de un gato pequeño
        keywords:
          type: string
          description: Palabras que sirven para clasificar la imagen
          example: animal gato
        author:
          type: string
          description: Nombre del autor de la imagen
          example: Juan
        uploader:
          type: string
          description: Nombre del usuario que ha subido la imagen
          example: Andres
        captureDate:
          type: string
          format: date
          description: Fecha de captura de la imagen, formato YYYY-MM-DD
          example: "2022-11-10"
    ImageMultipartForm:
      type: object
      properties:
        title:
          type: string
          description: Título de la imagen
          example: Gato
        description:
          type: string
          description: Descripción de la imagen
          example: Imagen de un gato pequeño
        keywords:
          type: string
          description: Palabras que sirven para clasificar la imagen
          example: animal gato
        author:
          type: string
          description: Nombre del autor de la imagen
          example: Juan
        uploader:
          type: string
          description: Nombre del usuario que ha subido la imagen
          example: Andres
        capture:
          type: string
          format: date
          description: Fecha de captura de la imagen, formato YYYY-MM-DD
          example: "2022-11-10"
        filename:
          type: string
          description: Nombre del fichero de la imagen
          example: gato.jpg
        file:
          type: string
          format: binary
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header

